### ISSUE TITLE
Switching from Plex to Plexpass

### ISSUE THREAD

**Issue by gdreelin** [binhex/arch-plexpass#16]
Binhex,  I loaded your Plex version a while ago but I have had a Plex Pass of years. I wanted to cut over to Plexpass version. Is there an easy way to go about doing this without having to rebuild the Plex server database?

**Comment by digitalit** [comment]
@gdreelin did you migrate to Plexpass version and if so how and what will you get over Plex version?

**Comment by gdreelin** [comment]
> @gdreelin did you migrate to Plexpass version and if so how and what will you get over Plex version?

Well I ended up going over to the plexinc version of the docker instead that includes PlexPass. I never go any response on this so just started over.
