### ISSUE TITLE
DVR preview release

### ISSUE THREAD

**Issue by benderstwin** [binhex/arch-plexpass#4]
Not really an issue, more of a request.  This pulls the PMS from the AUR repo which doesn't have the preview release of Plex that includes DVR functionality.  I use your docker container in unraid.  Is there a not so difficult way for a user to clone your container and modify it to use the preview release version?  Any help you might be able to provide is GREATLY appreciated.

I have an HDHomerun and would love to put it use :)

**Comment by binhex** [comment]
I just had a look on aur and saw you're comment against plexpass :-) so yeah if that guy creates a package for it then you could simply clone what I have and change the package name I reference in the code and it should build fine. Alternatively do what he suggested, download the package tarball for plexpass unpack it and change what the package downloads to point at the DVR branch, then upload it somewhere and download this during docker build time.
