### ISSUE TITLE
Create arch-ombi?

### ISSUE THREAD

**Issue by fryfrog** [binhex/arch-plexpass#6]
Hey @binhex, I don't know a better way to make a suggestion... but I noticed you don't have an ombi docker image. It looks like ombi v3 is a re-write and just had a pre-release, might be a good time to create one.

I've got an updated PKGBUILD for the AUR package of it, if that helps. I don't actually know if you use aur packages inside your dockers. :)

Is there a better way to make little suggestions? Do you hang out on any irc or discord?

**Comment by binhex** [comment]
Hi fry frog I currently don't have the time I'm afraid to work on a new docker image so this will have to be parked and I will review the situation in 6 months.
