### ISSUE TITLE
No Webgui option with unraid 6.7.0-rc1 or rc2

### ISSUE THREAD

**Issue by CanonCan** [binhex/arch-plexpass#9]
Hey Binhex using unRaid 6.7.0 both rc1 and now rc2 i no longer see a webgui option for plexpass version of your docker...manually entering the url works though so the docker itself is loading up

thought i'd give you a heads up

**Comment by ptr727** [comment]
Just encountered the same, upgraded to 6.7.0 public release, no more webgui.

**Comment by CanonCan** [comment]
Yeah luckily I assigned a static up and dns name so can manually load it up in the browser

**Comment by binhex** [comment]
when you say no more webgui you mean no link when you left click the plex icon?, so no 'WebUI'

**Comment by CanonCan** [comment]
thats right @binhex the left click drop down has been missing since unRAID 6.7.0 RC1 and now thats its officially released it should be addressed when you can

here is a screenshot from one of my unRAID servers

<img width="184" alt="Screen Shot 2019-05-13 at 10 16 41 AM" src="https://user-images.githubusercontent.com/31594024/57637338-69960a00-7568-11e9-887d-d67286ab6507.png">

**Comment by binhex** [comment]
I've updated to 6.7.0 and the web UI link is still present on a left click so it must be something to do with the template perhaps you have an older template or perhaps the new template has a bug in it I'll need to investigate further.

**Comment by CanonCan** [comment]
Sounds good I have two servers doing this downloader directly through unRaid’s App Store.   Just out at the moment if you need any other logs or screenshots let me know I’ll grab them when I get home in about an hour

**Comment by ptr727** [comment]
I have a similar UI menu, the Web link is no longer present for BinHex-PlexPass, but still there for BinHex- Sonarr, Radarr, and SabNzbd.

**Comment by binhex** [comment]
found the issue, its related to switching from host mode (correct and default network type) to bridge or custom bridge, excerpt from conversation on unraid forum:-

> 
> ok bit of quick testing, here is what is going on:-
> 
> firstly this container is supposed to run in host mode, this means no defined ports (not re quired as it talks directly on the hosts network). You then switched the network type from 'host' to 'bridge' or 'custom bridge', the problem now is you wont be able to connect to the container because there are no defined ports, and because there are no ports defined the web ui link wont show (as there are no ports to map the link to).
> 
> so two ways around this:-
> 
> 1. dont change it from host mode and be happy, you will see the web ui link.
> 2. switch to bridge or custom bridge and define the required ports for plex, you wll then magically see the web ui link will show (tested this).
>
